#!/bin/bash

# Clean up a bit more since may be using the starting directory to work.
rm -rf binder

# This must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts.
exec "$@"
