#!/bin/bash

# clean up a bit more since may be using the starting directory to work
rm -rf binder

# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
