#pragma cling load("/srv/conda/envs/notebook/lib/libarmadillo.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libmlpack.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_serialization.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_unit_test_framework.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_program_options.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_system.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_system.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_thread.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_iostreams.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libboost_filesystem.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libomp.so")
#pragma cling load("/srv/conda/envs/notebook/lib/libpython3.so")
#pragma cling add_include_path("/srv/conda/envs/notebook/include/python3.9m/")

#define ARMA_DONT_USE_WRAPPER
